name: forms_plus
description: A package for creating extensible type safe forms.
version: 1.0.0+3
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
